FROM openjdk:11
WORKDIR usr/src
ADD ./target/recommendation-service-0.0.1-SNAPSHOT.jar /usr/src/recommendation-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","recommendation-service-0.0.1-SNAPSHOT.jar"]
